# Tusk — build, install, and release the GUI app and the `tusk` CLI.
#
#   make            build everything and assemble dist/Tusk.app
#   make install    install Tusk.app to /Applications and `tusk` onto PATH
#   make uninstall  remove both
#   make release    signed + notarized + stapled DMG, ready to upload  <-- shipping
#   make clean      remove build + dist output
#
# Release pipeline (each depends on the previous):
#   bundle -> sign -> dmg -> notarize
# One-time setup for signing is documented in docs/RELEASING.md.

APP_NAME  := Tusk
# Version is the latest git tag (v0.1.1 -> 0.1.1). Falls back to a dev marker
# when there is no tag or no git metadata (e.g. building from a source tarball).
VERSION   := $(shell git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
VERSION   := $(if $(strip $(VERSION)),$(VERSION),0.0.0-dev)
CONFIG    := release

BUILD_DIR := .build/$(CONFIG)
DIST_DIR  := dist
APP       := $(DIST_DIR)/$(APP_NAME).app
DMG       := $(DIST_DIR)/$(APP_NAME)-$(VERSION).dmg

# Install locations. Prefer the Homebrew bin dir if present so `tusk` lands on PATH.
BREW_PREFIX := $(shell brew --prefix 2>/dev/null)
BINDIR    ?= $(if $(BREW_PREFIX),$(BREW_PREFIX)/bin,/usr/local/bin)
APPDIR    ?= /Applications

# Signing. SIGN_ID is auto-detected from the login keychain; override on the
# command line if you have more than one Developer ID.
SIGN_ID ?= $(shell security find-identity -v -p codesigning 2>/dev/null | grep 'Developer ID Application' | head -1 | sed 's/.*"\(.*\)"/\1/')
NOTARY_PROFILE ?= tusk
ENTITLEMENTS := packaging/Tusk.entitlements

.PHONY: all build gen-version bundle verify-bundle install uninstall register-mcp unregister-mcp \
        check-identity sign dmg notarize sync-cask release dist icon clean

all: bundle

build: gen-version
	swift build -c $(CONFIG)

# Keep the compiled-in version constant (Sources/TuskCore/Version.swift, read by
# `tusk version` and the MCP serverInfo) in lockstep with $(VERSION). Only rewrites
# the file when the value actually changes, so it doesn't force a recompile of
# TuskCore on every build.
gen-version:
	@ver='$(VERSION)'; f=Sources/TuskCore/Version.swift; \
	 new=$$(printf '%s\n' \
	   "// Generated by 'make gen-version' -- do not edit by hand." \
	   "// Version is derived from the git tag; see VERSION in the Makefile." \
	   "public enum TuskVersion {" \
	   "    public static let current = \"$$ver\"" \
	   "}"); \
	 if [ ! -f "$$f" ] || [ "$$(cat "$$f")" != "$$new" ]; then \
	   printf '%s\n' "$$new" > "$$f"; echo "gen-version: wrote $$f ($$ver)"; \
	 fi

# Regenerate packaging/AppIcon.icns from the CoreGraphics renderer.
icon:
	@rm -rf "$(DIST_DIR)/AppIcon.iconset" && mkdir -p "$(DIST_DIR)/AppIcon.iconset"
	@swiftc -O packaging/makeicon.swift -o "$(DIST_DIR)/makeicon"
	@"$(DIST_DIR)/makeicon" "$(DIST_DIR)/AppIcon.iconset"
	@iconutil -c icns "$(DIST_DIR)/AppIcon.iconset" -o packaging/AppIcon.icns
	@echo "Regenerated packaging/AppIcon.icns"

# Assemble Tusk.app: the GUI binary, the CLI, and their vendored dependencies.
#
# Both binaries link Homebrew's libpq (which itself pulls in openssl@3 and krb5)
# by absolute path, so bundle-dylibs.sh vendors that whole dependency tree into a
# Frameworks/ dir and rewrites the load paths. Without it the app only runs on a
# machine that happens to have the same Homebrew kegs.
#
# The CLI lives INSIDE the bundle rather than beside it, so that a single Tusk.app
# is the whole product: one thing to sign, one thing to notarize, one thing to drag
# out of a DMG. `install` and the Homebrew cask symlink it onto PATH as `tusk` (the
# way VS Code ships `code`). It shares the app's vendored dylibs via
# @executable_path/../Frameworks.
#
# It is named `tuskcli` in here, NOT `tusk`: macOS filesystems are case-insensitive,
# so Contents/MacOS/tusk and Contents/MacOS/Tusk are the same file and the CLI would
# silently overwrite the GUI binary. The symlink is what carries the `tusk` name.
bundle: build
	@rm -rf "$(APP)"
	@mkdir -p "$(APP)/Contents/MacOS" "$(APP)/Contents/Resources" "$(APP)/Contents/Frameworks"
	@cp "$(BUILD_DIR)/$(APP_NAME)" "$(APP)/Contents/MacOS/$(APP_NAME)"
	@cp "$(BUILD_DIR)/tuskcli" "$(APP)/Contents/MacOS/tuskcli"
	@chmod +x "$(APP)/Contents/MacOS/tuskcli"
	@sed 's/__VERSION__/$(VERSION)/g' packaging/Info.plist.in > "$(APP)/Contents/Info.plist"
	@cp packaging/AppIcon.icns "$(APP)/Contents/Resources/AppIcon.icns"
	@install_name_tool -add_rpath "@executable_path/../Frameworks" "$(APP)/Contents/MacOS/$(APP_NAME)" 2>/dev/null || true
	@install_name_tool -add_rpath "@executable_path/../Frameworks" "$(APP)/Contents/MacOS/tuskcli" 2>/dev/null || true
	@bash packaging/bundle-dylibs.sh "$(APP)/Contents/Frameworks" \
		"$(APP)/Contents/MacOS/$(APP_NAME)" "$(APP)/Contents/MacOS/tuskcli"
	@codesign --force --sign - "$(APP)/Contents/MacOS/tuskcli" 2>/dev/null
	@codesign --force --sign - "$(APP)" 2>/dev/null
	@# Guard the case-collision bug above: both binaries must survive, at full size.
	@test -f "$(APP)/Contents/MacOS/tuskcli" || { echo "FAIL: CLI missing from bundle"; exit 1; }
	@if [ "$$(stat -f%z "$(APP)/Contents/MacOS/$(APP_NAME)")" -lt 1000000 ]; then \
		echo "FAIL: $(APP_NAME) binary is too small — the CLI clobbered the GUI."; exit 1; \
	fi
	@echo "Built $(APP) (GUI + embedded tuskcli)"

# Fail loudly if anything in the bundle still points at Homebrew — the exact bug
# that ships an app which launches here and crashes everywhere else.
verify-bundle:
	@echo "Checking for absolute non-system dylib paths..."
	@! otool -L "$(APP)/Contents/MacOS/$(APP_NAME)" "$(APP)/Contents/MacOS/tuskcli" $(APP)/Contents/Frameworks/*.dylib 2>/dev/null \
		| grep -E '^\s+/(opt|usr/local)/' \
		|| { echo "FAIL: bundle still references Homebrew paths above."; exit 1; }
	@echo "OK: no Homebrew paths. Bundle is self-contained."

# --- Release: sign -> dmg -> notarize -------------------------------------------

check-identity:
	@if [ -z "$(SIGN_ID)" ]; then \
		echo "ERROR: no 'Developer ID Application' certificate in your keychain."; \
		echo "       Xcode > Settings > Accounts > Manage Certificates > + > Developer ID Application"; \
		echo "       See docs/RELEASING.md."; \
		exit 1; \
	fi
	@echo "Signing identity: $(SIGN_ID)"

# Sign inside-out: nested code first, bundle last. codesign seals what it finds,
# so signing the outer bundle before the dylibs would seal unsigned libraries and
# fail notarization. (Apple explicitly advises against --deep for distribution.)
#
# This must run AFTER bundle-dylibs.sh: install_name_tool invalidates signatures,
# so any signing done before path rewriting is destroyed by it.
sign: bundle verify-bundle check-identity
	@bash packaging/sign-app.sh "$(APP)" "$(SIGN_ID)" "$(ENTITLEMENTS)"
	@echo "Signed $(APP)"

# Notarization happens TWICE, and the order matters.
#
# A stapled ticket is what lets Gatekeeper approve the app with no network. The
# ticket is attached to a specific artifact, so stapling the DMG does nothing for
# the app a user drags OUT of it. If we only stapled the DMG, the installed app
# would carry no ticket and a first launch offline would fail to verify.
#
# So: notarize the app, staple the app, and only THEN build the DMG around the
# already-stapled app — and notarize/staple the DMG too, so the disk image itself
# also opens cleanly. Both artifacts end up self-sufficient offline.
notarize-app: sign
	@echo "Submitting app to Apple (1-5 minutes)..."
	@rm -f "$(DIST_DIR)/notarize-app.zip"
	@ditto -c -k --keepParent "$(APP)" "$(DIST_DIR)/notarize-app.zip"
	xcrun notarytool submit "$(DIST_DIR)/notarize-app.zip" --keychain-profile "$(NOTARY_PROFILE)" --wait
	xcrun stapler staple "$(APP)"
	@rm -f "$(DIST_DIR)/notarize-app.zip"

dmg: notarize-app
	@rm -f "$(DMG)"
	@rm -rf "$(DIST_DIR)/dmgroot"
	@mkdir -p "$(DIST_DIR)/dmgroot"
	@cp -R "$(APP)" "$(DIST_DIR)/dmgroot/"
	@ln -s /Applications "$(DIST_DIR)/dmgroot/Applications"
	@hdiutil create -volname "$(APP_NAME)" -srcfolder "$(DIST_DIR)/dmgroot" \
		-ov -format UDZO "$(DMG)" >/dev/null
	@rm -rf "$(DIST_DIR)/dmgroot"
	@codesign --force --timestamp --sign "$(SIGN_ID)" "$(DMG)"
	@echo "Wrote $(DMG)"

notarize: dmg
	@echo "Submitting DMG to Apple (1-5 minutes)..."
	xcrun notarytool submit "$(DMG)" --keychain-profile "$(NOTARY_PROFILE)" --wait
	xcrun stapler staple "$(DMG)"
	@echo
	@echo "Verifying Gatekeeper acceptance..."
	@spctl -a -t open --context context:primary-signature -v "$(DMG)"
	@spctl -a -vv "$(APP)"
	@xcrun stapler validate "$(APP)" | tail -1
	@echo
	@echo "Release ready: $(DMG)"
	@shasum -a 256 "$(DMG)"

# Sync the Homebrew cask to the freshly built release: version from the git tag,
# sha256 from the final (stapled) DMG. Runs after notarize so it hashes the exact
# artifact users download — keeping the tap from ever drifting out of sync.
sync-cask: notarize
	@sha=$$(shasum -a 256 "$(DMG)" | awk '{print $$1}'); \
	 sed -i '' -e 's/^\( *version \).*/\1"$(VERSION)"/' \
	           -e "s#^\( *sha256 \).*#\1\"$$sha\"#" packaging/Casks/tusk.rb; \
	 echo "sync-cask: packaging/Casks/tusk.rb -> version $(VERSION), sha256 $$sha"

release: sync-cask

# `tusk` on PATH is a symlink into the installed bundle, not a copy: one binary,
# one set of dylibs, and it can never drift out of sync with the app.
#
# Sign with the real Developer ID if one is available, rather than leaving the
# ad-hoc signature from `bundle`. Tusk keeps database passwords in the login
# keychain, and keychain ACLs are bound to the app's code-signing identity. An
# ad-hoc signature has no stable identity — its hash changes on every build — so
# each rebuild looks like a DIFFERENT app to the keychain and macOS challenges you
# for your login password all over again. Signing with the Developer ID gives the
# app one stable identity across rebuilds, and the prompt stops.
install: bundle
	@if [ -n "$(SIGN_ID)" ]; then \
		echo "Signing with: $(SIGN_ID)"; \
		bash packaging/sign-app.sh "$(APP)" "$(SIGN_ID)" "$(ENTITLEMENTS)"; \
	else \
		echo "note: no Developer ID certificate found — installing ad-hoc signed."; \
		echo "      macOS will re-prompt for keychain access after every rebuild."; \
	fi
	@rm -rf "$(APPDIR)/$(APP_NAME).app"
	cp -R "$(APP)" "$(APPDIR)/"
	@mkdir -p "$(BINDIR)"
	ln -sf "$(APPDIR)/$(APP_NAME).app/Contents/MacOS/tuskcli" "$(BINDIR)/tusk"
	@mkdir -p "$(HOME)/TuskProjects"
	@echo "Installed $(APPDIR)/$(APP_NAME).app and linked $(BINDIR)/tusk"
	@echo "Workspace folder ready at $(HOME)/TuskProjects"
	@$(MAKE) --no-print-directory register-mcp

# Register the MCP server with Claude Code at user scope (available in all
# projects). Best-effort: skips gracefully if the `claude` CLI isn't installed.
register-mcp:
	@if command -v claude >/dev/null 2>&1; then \
		claude mcp remove tusk -s user >/dev/null 2>&1 || true; \
		claude mcp add tusk -s user -- "$(BINDIR)/tusk" mcp >/dev/null && \
		echo "Registered MCP server 'tusk' with Claude Code (user scope)."; \
	else \
		echo "Note: 'claude' CLI not found — skipped MCP registration."; \
		echo "      To add it later:  claude mcp add tusk -s user -- $(BINDIR)/tusk mcp"; \
	fi

unregister-mcp:
	@command -v claude >/dev/null 2>&1 && claude mcp remove tusk -s user >/dev/null 2>&1 || true

uninstall: unregister-mcp
	rm -rf "$(APPDIR)/$(APP_NAME).app"
	rm -f "$(BINDIR)/tusk"
	@echo "Removed $(APPDIR)/$(APP_NAME).app, $(BINDIR)/tusk, and the Claude MCP entry"

# The DMG is now the one and only release artifact — the website download AND the
# Homebrew cask both point at it, so there's no second artifact to drift.
dist: release

clean:
	rm -rf "$(DIST_DIR)"
	swift package clean
